---
- name: install yum packages
  yum:
    state: installed
    name:
    - docker
    - dstat
    - lsof
    - bash-completion
    - time
    - tmux
    - git
    - python-devel
    - openssl-devel
    - python-pip
    - sysstat
    - iptables-services
  become: True

- name: disable selinux to permit using hosts docker for builds
  selinux:
    state: disabled
  become: True

- name: disable selinux in docker options
  copy:
    dest: /etc/sysconfig/docker
    content: |
      OPTIONS='--selinux-enabled=false --log-driver=journald --signature-verification=false'
      if [ -z "${DOCKER_CERT_PATH}" ]; then
          DOCKER_CERT_PATH=/etc/docker
      fi
      /sbin/setsebool -P docker_transition_unconfined 1
  become: True

- name: load overlay kernel module for docker
  modprobe:
    name: overlay
    state: present
  become: True

- name: create docker group
  group:
    name: docker
    state: present
  become: True

- name: add ansible user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: True

- name: install docker-py on remote machine
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  become: True
  with_items:
    - { name: "docker", version: "2.2.1"}
    - { name: "docker-py", version: "1.10.5" }
    - { name: "docker-compose", version: "1.9.0" }

- name: format docker storage
  filesystem:
    dev: "{{ docker_storage_device }}"
    fstype: xfs
  when: docker_storage_device is defined
  become: True

- name: remove default mount
  mount:
    path: /mnt
    src: /dev/vdb
    state: absent
  become: True
  when: docker_storage_device is defined

- name: mount docker storage
  mount:
    path: /var/lib/docker
    src: "{{ docker_storage_device }}"
    fstype: xfs
    opts: noatime
    state: mounted
  when: docker_storage_device is defined
  become: True

- name: setup docker storage
  blockinfile:
    dest: /etc/sysconfig/docker-storage-setup
    block: |
      {% if docker_storage_driver is defined %}
      STORAGE_DRIVER={{ docker_storage_driver }}
      {% endif %}
      {% if docker_storage_device is defined %}
      DEVS={{ docker_storage_device }}
      {% endif %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  become: True

- name: start docker
  service: name=docker state=started enabled=yes
  become: True

- name: upgrade pip so package installs are not broken
  pip:
    name: pip
    state: latest
  become: True

- name: make parent dir
  file:
    path: /srv/gitlab-runner/config/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    setype: svirt_sandbox_file_t
    mode: 0744
  become: True

- name: make cert dir
  file:
    path: /srv/gitlab-runner/config/certs/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    setype: svirt_sandbox_file_t
    mode: 0744
  become: True
  when: self_signed_certificate|length > 1

- name: upload self-signed cert
  copy:
    dest: /srv/gitlab-runner/config/certs/ca.crt
    content: "{{ self_signed_cert }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    setype: svirt_sandbox_file_t
    mode: 0744
  become: True
  when: self_signed_certificate|length > 1

- include: gitlab_runner.yml
  with_items: "{{ runner_configs }}"
